version: '3.3'

services:
  mssql:
    container_name: sql-server-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: Express
    ports:
      - 1433:${DB_PORT}
    volumes:
      - mssql-volume:/var/opt/mssql

volumes:
  mssql-volume:
